In [2]:
import numpy as np
a=np.array([1,2,3,4,5])
print(type(a))

<class 'numpy.ndarray'>


In [5]:
b=np.zeros((3,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
c=np.array(([1,2,3],[4,5,6]))
print(c.shape)

(2, 3)


In [13]:
c=np.ones((3,2))
print(c)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [27]:
b=np.full((3,3),10)
print(b)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [30]:
b=np.eye((4))
print(b)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [33]:
b=np.random.random((3,3))
print(b)

[[0.78177764 0.4423916  0.21901204]
 [0.56449096 0.31536584 0.35388242]
 [0.70521582 0.46412296 0.82109208]]


In [ ]:
np.linspace(2.0,3.0,num=5)

In [44]:
a=np.array(([1,2,3,4,5,6,7,8,9]))
print(a)

[1 2 3 4 5 6 7 8 9]


In [3]:
np.linspace(2.0,3.0,num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [4]:
np.linspace(2.0,3.0,num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [47]:
x= np.array([1,2] , dtype = np.int64)
print(x)

[1 2]


In [5]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print((a))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
b=a[:2,1:3]
print((b))

[[2 3]
 [6 7]]


In [7]:
print(a[0,1])

2


In [8]:
print(a[0,1])

2


In [9]:
print(a[:2,1:3])

[[2 3]
 [6 7]]


In [10]:
print(a[0:2,1:2])

[[2]
 [6]]


In [11]:
print(a[2:3,0:2])

[[ 9 10]]


In [13]:
print(a[:2,1:])
print(a[-3:-1,-2:-1])
print(a[-2:1,1:3])
print(a[-2:1,1:3])

[[2 3 4]
 [6 7 8]]
[[3]
 [7]]
[]
[]


In [14]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
print(a[[0,1,2],[0,1,0]])

[1 4 5]


In [16]:
print(np.array([a[0,0],a[1,1],a[2,0]]))
print(a[[0,0],[1,1]])
print(np.array([a[0,1],a[0,1]]))

[1 4 5]
[2 2]
[2 2]


In [17]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [18]:
b=np.array([0,2,0,1])
print(b)

[0 2 0 1]


In [19]:
print(a[np.arange(4),b])

[ 1  6  7 11]


In [20]:
a[np.arange(4),b]+=10
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [21]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
bool_idx=(a>2)
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [22]:
print(a[bool_idx])

[3 4 5 6]


In [23]:
print(a[a>2])


[3 4 5 6]


In [24]:
import numpy as np
x=np.array([1,2])
print(x.dtype)

int64


In [25]:
x=np.array([1.0,2.0])
print(x.dtype)

float64


In [26]:
x=np.array([1,2],dtype=np.int64)
print(x.dtype)

int64


In [27]:
import numpy as np
a=np.array([[1,2],[3,4]])
eigenvalues,eigenvectors=np.linalg.eig(a)
print("eigenvalues:")
print(eigenvalues)
print("\n eigenvectors:")
print(eigenvectors)

eigenvalues:
[-0.37228132  5.37228132]

 eigenvectors:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [28]:
import numpy as np
x=np.array([[1,2],[3,4]],dtype=np.float64)
y=np.array([[5,6],[7,8]],dtype=np.float64)
print(x+y)

[[ 6.  8.]
 [10. 12.]]


In [29]:
print(np.add(x,y))
print(x-y)
print(np.subtract(x,y))
print(np.divide(x,y))
print(x/y)
print(x*y)

[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[ 5. 12.]
 [21. 32.]]


In [30]:
print(np.multiply(x,y))

[[ 5. 12.]
 [21. 32.]]


In [31]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [32]:
import numpy as np
x=np.array([[1,2],[3,4]])
print(x)

[[1 2]
 [3 4]]


In [33]:
print(x.T)

[[1 3]
 [2 4]]


In [34]:
v=np.array([1,2,3])
print(v)
print(v.T)

[1 2 3]
[1 2 3]
